### ISSUE TITLE
Firefox blocks access because the certificate expired this morning

### ISSUE THREAD

**Issue by plater** [bmwiedemann/susepkginfo#3]
I think it's also a bug in firefox because there wasn't an option to make an exeption. I had to set my clock to yesterdays date to acess the site.
maintainer.zq1.de uses an invalid security certificate. The certificate expired on 29/09/2017 09:11. The current time is 29/09/2017 15:50. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by bmwiedemann** [comment]
solved by updating the cert.

firefox behaviour is intentional, because the server is announcing "HSTS", telling it to better fail than be insecure. Not really needed though, so I'll deactivate it.
